# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)
mmistakes/minimal-mistakes
